### PR TITLE
EDITS

### PR DESCRIPTION
**Pull request by gabolera**
**NEW**: The function delete note is working.
**EDIT**: Create a note make using CBV (Class Based Views) (Recommended)
**EDIT**: Templates folder into root folder of application (Recommended)

Making the 'edit note' i don't finished yet.

if you can have a any question important, please send a message for me on my email. _k.gabriel.andreazza_ via gmail

I'll finish the 'edit note'

### CODE REVIEW

**Comment by gabolera** [comment]
For resolve this conflict. 
Copy your index.js and styles.css

Dont replace views.py and index.html (these files must be mine. or application don't work)
The index.html have a codes is diffrent of your default

Your can re-write the html, but caution on edit the code, to readapt your JS and CSS.

**Comment by eshaan7** [comment]
I cannot merge this with my master branch coz you have completely made your own HTML/CSS files. Plus, I did not now about the CBV  that's something I will have to lookup.

**Review by eshaan7 — APPROVED** [review]

**Comment by gabolera** [comment]
errors in HTML is simple. this was because I removed the templates folder and the static folder from within the notes folder. and moved them to the root of the application, this is a hint of orgazinação so that when you have some other application, all HTML's are together. 

And views is all ok.

For your understand better what i made into 'views'
https://docs.djangoproject.com/pt-br/2.1/ref/class-based-views/generic-editing/

**Comment by eshaan7** [comment]
I've merged your rqst on a new branch. I would use my own templates/static pages adn configure the views accordingly. Thanks :)

**Comment by gabolera** [comment]
Yes course, have a good study :)
If you need any help and i can, you can send a message for me: **k.gabriel.andreazza** <2> into gmail host

**Pull request merged**
